### PR TITLE
Login form using html Tailwind css

### PR DESCRIPTION
**Pull request by dhruvabhat24**
https://github.com/avinash201199/Login-Signup-templates/assets/122305929/d92f205f-4bb6-4ba8-b204-7bbd11638608

### CODE REVIEW

**Comment by avinash201199** [comment]
please remove node modules

**Comment by avinash201199** [comment]
also you can contribute in readme file, like how people can contribute in this repo, first fork this repo , and if they want to add their login template then they should create folder with their name , inside their folder they have to put their source code files

**Comment by dhruvabhat24** [comment]
Ok I will remove the node modules. For README I will raise the issue first. And please assign it to me

**Comment by avinash201199** [comment]
you can also add this video in your login template folder inside readme so that people can see it directly

**Comment by avinash201199** [comment]
are you interested to maintain this repo ? I will add you as a maintainer and after that I will share this repo in my network , lots of people will contribute and you have to maintain it py reviewing and accepting pr!

**Comment by dhruvabhat24** [comment]
Ok I will add

**Pull request merged**
